version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The FARMIZO_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     FARMIZO_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - farmizo-sqldata:/var/opt/mssql

  nosqldata:
    ports:
      - "27017:27017"
    volumes:
      - farmizo-nosqldata:/data/db

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7104
      - XamarinCallback=http://${FARMIZO_PROD_EXTERNAL_DNS_NAME_OR_IP}:7105/xamarincallback
      - ConnectionString=${FARMIZO_AZURE_IDENTITY_DB:-Server=sqldata;Database=Farmizo.Services.IdentityDb;User Id=sa;Password=Pass@word}
      - MvcClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7100
      - LocationApiClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7109
      - MarketingApiClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7110
      - BasketApiClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7103
      - OrderingApiClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7102
      - MobileShoppingAggClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7120
      - WebShoppingAggClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7121
      - WebhooksApiClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7113
      - WebhooksWebClient=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7114
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "7105:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${FARMIZO_AZURE_CATALOG_DB:-Server=sqldata;Database=Farmizo.Services.CatalogDb;User Id=sa;Password=Pass@word}
      - PicBaseUrl=${FARMIZO_STORAGE_CATALOG_URL}
      - EventBusConnection=${FARMIZO_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FARMIZO_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FARMIZO_SERVICE_BUS_PASSWORD}
      - AzureStorageAccountName=${FARMIZO_AZURE_STORAGE_CATALOG_NAME}
      - AzureStorageAccountKey=${FARMIZO_AZURE_STORAGE_CATALOG_KEY}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/catalog-api
    ports:
      - "7101:80"
      - "9101:81"

  webhooks-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${FARMIZO_AZURE_WEBHOOKS_DB:-Server=sqldata;Database=Farmizo.Services.WebhooksDb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${FARMIZO_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${FARMIZO_SERVICE_BUS_USERNAME}
      - EventBusPassword=${FARMIZO_SERVICE_BUS_PASSWORD}
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7105
    ports:
      - "7113:80"

  webshoppingapigw:
    volumes:
      - ./ApiGateways/Envoy/config/webshopping:/etc/envoy
    ports:
    - "7202:80"
    - "15202:8001"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket-api
      - urls__catalog=http://catalog-api
      - urls__orders=http://ordering-api
      - urls__identity=http://identity-api
      - urls__grpcBasket=http://basket-api:81
      - urls__grpcCatalog=http://catalog-api:81
      - urls__grpcOrdering=http://ordering-api:81
      - CatalogUrlHC=http://catalog-api/hc
      - OrderingUrlHC=http://ordering-api/hc
      - IdentityUrlHC=http://identity-api/hc
      - BasketUrlHC=http://basket-api/hc
      - MarketingUrlHC=http://marketing-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - LocationUrlHC=http://locations-api/hc
      - IdentityUrlExternal=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7105
    ports:
      - "7121:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PurchaseUrl=http://webshoppingapigw
      - IdentityUrl=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7105
      - MarketingUrl=http://webmarketingapigw
      - SignalrHubUrl=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7202
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "7100:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://webmvc/hc
      - HealthChecksUI__HealthChecks__1__Name=Web Shopping Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webshoppingagg/hc
      - HealthChecksUI__HealthChecks__2__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://catalog-api/hc
      - HealthChecksUI__HealthChecks__3__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://identity-api/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "7107:80"

  webhooks-client:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Token=6168DB8D-DC58-4094-AF24-483278923590      # Webhooks are registered with this token (any value is valid) but the client won't check it
      - IdentityUrl=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7105
      - CallBackUrl=http://${FARMIZO_EXTERNAL_DNS_NAME_OR_IP}:7114
      - WebhooksUrl=http://webhooks-api
      - SelfUrl=http://webhooks-client/
    ports:
      - "7114:80"

volumes:
  farmizo-sqldata:
    external: false
  farmizo-nosqldata:
    external: false
  farmizo-basketdata:
    external: false

